import photonic.views.apiproxy
import photonic.views.home
import photonic.views.auth
import photonic.views.users
import photonic.views.rbac
import photonic.views.tenants
import photonic.views.endpoints
import photonic.views.domains
import photonic.views.roles
